name: CI
on:
  # Trigger the workflow on push to the master branch
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: OpenShift Action
      uses: redhat-developer/openshift-actions@v1.1
      with:
        version: 'latest'
        openshift_server_url: 'https://api.us-west-1.starter.openshift-online.com:6443' #${{ secrets.OPENSHIFT_SERVER_URL }}
        parameters: '{"apitoken": "cy9soOrOPYUdvfPLsHQ4fRLUFFIteSIAndEKyOsIu9c", "acceptUntrustedCerts": "true"}'
        #parameters: '{"apitoken": "${{ secrets.API_TOKEN }}", "acceptUntrustedCerts": "true"}'
        #parameters: '{"username": "${{ secrets.USERNAME }}", "password": "${{ secrets.PASSWORD }}", "acceptUntrustedCerts": "true"}'
        cmd: |
          'version'
          'start-build book-helloworld-my --follow'
          'status'